# Generated by Django 3.2 on 2021-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Roll', models.CharField(max_length=50, null=True)),
                ('Age', models.CharField(max_length=50, null=True)),
                ('Std', models.CharField(choices=[('v', 'v'), ('ii', 'ii'), ('x', 'x'), ('ix', 'ix'), ('i', 'i'), ('iii', 'iii'), ('vii', 'vii'), ('viii', 'viii'), ('iv', 'iv'), ('vi', 'vi')], max_length=50, null=True)),
                ('Convience', models.CharField(choices=[('Liberary', 'Liberary'), ('Both', 'Both'), ('Bus', 'Bus'), ('None', 'None')], max_length=50, null=True)),
                ('profile_pic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
