# Generated by Django 3.2 on 2021-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210729_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Both', 'Both'), ('None', 'None'), ('Liberary', 'Liberary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('vii', 'vii'), ('x', 'x'), ('v', 'v'), ('iv', 'iv'), ('vi', 'vi'), ('ix', 'ix'), ('i', 'i'), ('ii', 'ii'), ('iii', 'iii'), ('viii', 'viii')], max_length=50, null=True),
        ),
    ]
