# Generated by Django 3.2 on 2021-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210729_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Both', 'Both'), ('Bus', 'Bus'), ('Liberary', 'Liberary'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('vii', 'vii'), ('iii', 'iii'), ('vi', 'vi'), ('viii', 'viii'), ('ix', 'ix'), ('iv', 'iv'), ('v', 'v'), ('i', 'i'), ('x', 'x'), ('ii', 'ii')], max_length=50, null=True),
        ),
    ]
