# Generated by Django 3.2 on 2021-07-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210729_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Liberary', 'Liberary'), ('None', 'None'), ('Bus', 'Bus'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('iii', 'iii'), ('vii', 'vii'), ('ix', 'ix'), ('i', 'i'), ('vi', 'vi'), ('viii', 'viii'), ('x', 'x'), ('v', 'v'), ('ii', 'ii'), ('iv', 'iv')], max_length=50, null=True),
        ),
    ]
