# Generated by Django 3.2 on 2021-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210729_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Liberary', 'Liberary'), ('Both', 'Both'), ('Bus', 'Bus'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('x', 'x'), ('viii', 'viii'), ('ii', 'ii'), ('v', 'v'), ('vi', 'vi'), ('vii', 'vii'), ('iii', 'iii'), ('iv', 'iv'), ('i', 'i'), ('ix', 'ix')], max_length=50, null=True),
        ),
    ]
