# Generated by Django 3.2 on 2021-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210729_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('None', 'None'), ('Liberary', 'Liberary'), ('Bus', 'Bus'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('vii', 'vii'), ('ix', 'ix'), ('vi', 'vi'), ('v', 'v'), ('ii', 'ii'), ('iii', 'iii'), ('x', 'x'), ('iv', 'iv'), ('viii', 'viii'), ('i', 'i')], max_length=50, null=True),
        ),
    ]
