# Generated by Django 3.2 on 2021-07-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210729_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Both', 'Both'), ('None', 'None'), ('Bus', 'Bus'), ('Liberary', 'Liberary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('v', 'v'), ('x', 'x'), ('viii', 'viii'), ('iii', 'iii'), ('i', 'i'), ('vi', 'vi'), ('vii', 'vii'), ('ii', 'ii'), ('iv', 'iv'), ('ix', 'ix')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
