# Generated by Django 3.2.4 on 2021-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210730_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Liberary', 'Liberary'), ('None', 'None'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('v', 'v'), ('iv', 'iv'), ('i', 'i'), ('ii', 'ii'), ('iii', 'iii'), ('viii', 'viii'), ('x', 'x'), ('ix', 'ix'), ('vi', 'vi'), ('vii', 'vii')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
