# Generated by Django 3.2.4 on 2021-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210730_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Liberary', 'Liberary'), ('None', 'None'), ('Both', 'Both'), ('Bus', 'Bus')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('iv', 'iv'), ('iii', 'iii'), ('v', 'v'), ('ix', 'ix'), ('vi', 'vi'), ('x', 'x'), ('vii', 'vii'), ('viii', 'viii'), ('i', 'i'), ('ii', 'ii')], max_length=50, null=True),
        ),
    ]
