# Generated by Django 3.2.4 on 2021-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20210730_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Both', 'Both'), ('Liberary', 'Liberary'), ('None', 'None'), ('Bus', 'Bus')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('i', 'i'), ('iv', 'iv'), ('vi', 'vi'), ('x', 'x'), ('v', 'v'), ('ii', 'ii'), ('viii', 'viii'), ('vii', 'vii'), ('ix', 'ix'), ('iii', 'iii')], max_length=50, null=True),
        ),
    ]
